environment:
  matrix:
      - TARGET: x86_64-pc-windows-msvc
      - TARGET: i686-pc-windows-msvc

install:
    - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
    - rustup-init.exe -y --default-host %TARGET%
    - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
    - rustc --version
    - cargo --version

build: false

test_script:
    - 'cargo test --all-features'
    - 'cd examples/server'
    - 'cargo check'
    - 'cd ../../examples/client'
    - 'cargo check'
